<?php

namespace MeetupBundle\Repository;

/**
 * ExtractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtractRepository extends \Doctrine\ORM\EntityRepository
{
}
