<?php

namespace MeetupBundle\Repository;

/**
 * GroupesTopicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupesTopicsRepository extends \Doctrine\ORM\EntityRepository
{
}
