<?php

namespace MeetupBundle\Repository;

/**
 * Groupes_TopicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Groupes_TopicsRepository extends \Doctrine\ORM\EntityRepository
{
}
