<?php

namespace MeetupBundle\Repository;

/**
 * GroupesPHPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupesPHPRepository extends \Doctrine\ORM\EntityRepository
{
}
