<?php

namespace MeetupBundle\Repository;

/**
 * GroupesPHPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupesPHPRepository extends \Doctrine\ORM\EntityRepository
{
    public function MembersByCity($topic, $ville)
   {
       $qb = $this->createQueryBuilder('g');

       $qb->select('SUM(g.members) AS membresTotal')
           ->addSelect('g.topic')
           ->where('g.topic = ?1')
           ->andwhere('g.city = ?2')
           ->groupBy('g.topic')
           ->setParameters(array( 1 => $topic, 2 => $ville));

       return $qb->getQuery()->getResult();
   }
   public function Graph()
  {
      $qb = $this->createQueryBuilder('g');

      $qb->select('SUM(g.members) AS membresTotal')
         ->addSelect('g.city')
         ->addSelect('g.topic')
         ->groupBy('g.topic')
          ;

      return $qb->getQuery()->getResult();
  }
}
