<?php

namespace MeetupBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * GroupesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupesRepository extends EntityRepository
{
    public function getMembresWithTopics(array $topicsNames)
    {
        $query = $em->createQuery(
        'SELECT g, t
         FROM MeetupBundle:Groupes g
         JOIN g.topics t
         ON 
         WHERE t.name = \'PHP\'
         ORDER BY g.members DESC'
        );



        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
