<?php

namespace MeetupBundle\Repository;

/**
 * GroupePhpRetroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupePhpRetroRepository extends \Doctrine\ORM\EntityRepository
{
}
