<?php

namespace MeetupBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TopicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicsRepository extends EntityRepository
{
	public function WordCloudByCity($ville)
   {
       $qb = $this->createQueryBuilder('t');

       $qb->select('COUNT(t.name) AS compte')
       	   ->addSelect('t.name')
           ->where('t.ville = ?1')
           ->groupBy('t.name')
           ->setMaxResults(50)
           ->orderBy('compte', 'DESC' )
           ->setParameters(array( 1 => $ville));

       return $qb->getQuery()->getResult();
   }
}
