<?php

namespace MeetupBundle\Repository;

/**
 * Villes_GroupesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Villes_GroupesRepository extends \Doctrine\ORM\EntityRepository
{
}
