user_login:
    path:     login
    defaults: { _controller: UserBundle:Security:login }

user_login_check:
    path:     login/check
    defaults: { _controller: UserBundle:Security:check }

user_register:
    path:     register
    defaults: { _controller: UserBundle:Registration:register }

user_confirmed:
    path:     confirmed
    defaults: { _controller: UserBundle:Registration:confirmed }
