event:
    path:     /event
    defaults: { _controller: MeetupBundle:Default:event }

groupe:
    path:     /groupe
    defaults: { _controller: MeetupBundle:Default:groupe }

topic:
    path:     /topic
    defaults: { _controller: MeetupBundle:Default:topic }

groupeTopic:
    path:     /groupesTopics
    defaults: { _controller: MeetupBundle:Default:groupesTopics }

user_accueil:
    path:     /user/accueil
    defaults: { _controller: MeetupBundle:Page:show }

user_ville:
    path:     /user/ville
    defaults: { _controller: MeetupBundle:Ville:show }
