meetup_homepage:
    path:     /
    defaults: { _controller: MeetupBundle:Default:index }

user_dashboard:
    path:     /user/dashboard
    defaults: { _controller: MeetupBundle:Default:index }

user_accueil:
    path:     /user/accueil
    defaults: { _controller: MeetupBundle:Page:show }
