event:
    path:     /event
    defaults: { _controller: MeetupBundle:Default:event }

groupe:
    path:     /groupe
    defaults: { _controller: MeetupBundle:Default:groupes }

topic:
    path:     /topic
    defaults: { _controller: MeetupBundle:Default:topics }

groupeTopic:
    path:     /groupesTopics
    defaults: { _controller: MeetupBundle:Default:groupesTopics }

groupePHP:
    path:     /groupePHP
    defaults: { _controller: MeetupBundle:Default:groupesPHP }

user_accueil:
    path:     /user/accueil
    defaults: { _controller: MeetupBundle:Page:show }

user_accueil_retro:
    path:     /user/accueil/{retroFin}/{retroDeb}
    defaults: { _controller: MeetupBundle:Page:showRetro }


user_accueilParis:
    path:     /user/accueil-paris
    defaults: { _controller: MeetupBundle:Page:showParis }

user_ville:
    path:     /user/{ville}
    defaults: { _controller: MeetupBundle:Ville:show }

extract:
    path:   /extract
    defaults: { _controller: MeetupBundle:Default:extract }
