event:
    path:     /event
    defaults: { _controller: MeetupBundle:Default:event }

user_dashboard:
    path:     /user/dashboard
    defaults: { _controller: MeetupBundle:Default:index }

user_accueil:
    path:     /user/accueil
    defaults: { _controller: MeetupBundle:Page:show }

user_ville:
    path:     /user/ville
    defaults: { _controller: MeetupBundle:Ville:show }